-- Q1. What is the total revenue generated by male vs. female customers ?
SELECT
 gender AS Gender,
 SUM(purchase_amount) as Revenue 
FROM
(SELECT
customer_id,
gender,
purchase_amount
FROM customer)t
GROUP BY gender ;

-- Q2. Which customers used a discount but still spent more than the average purchase amount ?
SELECT
customer_id,
purchase_amount
FROM customer 
WHERE discount_applied='Yes' AND purchase_amount >=(SELECT AVG(purchase_amount) FROM customer);

-- Q3. Which are the top 5 products with the highest average review rating ?
SELECT 
item_purchased,
ROUND(AVG(review_rating),1) "Average Product Rating"
FROM customer
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC
LIMIT 5;

-- Q4 Compare the average Purchase Amounts between Standard and Express Shipping.

SELECT
shipping_type,
ROUND(AVG(purchase_amount),1) 'Average Purchase Amount'
FROM 
(SELECT 
shipping_type,
purchase_amount
FROM customer
WHERE shipping_type='Express' OR shipping_type='Standard'
)t
GROUP BY shipping_type;

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
SELECT 
subscription_status,
COUNT(customer_id) as 'Customers',
ROUND(AVG(purchase_amount),1) as avg_spend,
SUM(purchase_amount) as total_revenue 
FROM customer
WHERE subscription_status in ('Yes','No')
GROUP BY subscription_status
Order by total_revenue, avg_spend desc ;

-- Q6 Which 5 products have the highest percentage of purchases with discount applied ? 
SELECT 
	item_purchased,
    ROUND(100* SUM(CASE 
    WHEN discount_applied = 'Yes' THEN 1 
    ELSE 0 END)/COUNT(*),2) as discount_rate 
FROM
	customer
GROUP BY item_purchased
ORDER BY discount_rate DESC 
LIMIT 5;

-- Q7 Segment customers into New,Returning, and Loyal based on their total number of preivous purchases, and show the count of each segment.
SELECT
    customer_segment,
	Count(customer_segment) AS 'Number of customers'
FROM
(SELECT 
	customer_id,
    previous_purchases,
    CASE 
		WHEN previous_purchases = 1 THEN 'New'
		WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
        ELSE 'Loyal'
        END AS customer_segment
	FROM customer
    )t
GROUP by customer_segment ;

-- Q8. What are the top 3 most purchased products within each category?
    SELECT
	item_rank,
    category,
    item_purchased,
    total_orders
FROM
(SELECT category,
item_purchased,
COUNT(customer_id) as total_orders,
ROW_NUMBER() OVER(PARTITION BY category ORDER BY COUNT(customer_id) DESC) as item_rank
FROM customer
GROUP BY category, item_purchased
)t
WHERE item_rank <=3;

-- Q9. Are customers who are repeating buyers (more than the 5 previous purchases) also likely to subscribe ?

SELECT
	COUNT(customer_id) as repeated_buyers,
    subscription_status
FROM customer
	WHERE previous_purchases > 5 
GROUP BY subscription_status ;

-- Q10. What is the revenue contribution of each age group ?
SELECT
	age_group,
    SUM(purchase_amount) AS 'Total Revenue'
FROM customer
GROUP BY age_group 
ORDER BY SUM(purchase_amount) DESC;